# \DeclareLyXModule{Hagenberg style}
# DescriptionBegin
#   Use the Hagenberg flavour of formatting theses.
# DescriptionEnd

# Hugo Hinterberger 2014

Format 48

Requires hgb

Provides cmap            1
Provides inputenc        1
Provides lmodern         1
Provides fontenc         1
Provides ifthen          1
Provides babel           1
Provides datetime        1
Provides graphicx        1
Provides url             1
Provides verbatim        1
Provides moreverb        1
Provides float           1
Provides caption         1
Provides exscale         1
Provides upquote         1
Provides amsmath         1
Provides amsfonts        1
Provides amsbsy          1
Provides xspace          1
Provides algorithm       1
Provides algorithmicx    1
Provides algpseudocode   1
Provides pseudocode      1
Provides color           1
Provides listingsutf8    1
Provides hyperref        1
Provides hypcap          1
Provides ifpdf           1
Provides enumitem        1

Style English
  Margin           First_Dynamic
  LatexType        Environment
  LatexName        english
  Category         Hagenberg
  InTitle          false
  ParIndent        ""
  LabelType        Above
  LabelString      "English text:"
  LabelSep         M
  LabelBottomSep   0
End

Style Deutsch
  Margin           First_Dynamic
  LatexType        Environment
  LatexName        german
  Category         Hagenberg
  InTitle          false
  ParIndent        ""
  LabelType        Above
  LabelString      "Deutscher Text:"
  LabelSep         M
  LabelBottomSep   0
End

Style "File List"
  Category         "Hagenberg"
  LatexType        Item_Environment
  LatexName        FileList
  ItemCommand      fitem
  LabelType        No_Label
  LabelString      "File list"
  EndLabelType     No_Label
  Argument         1
    Mandatory      1
    LabelString    "Path"
    Tooltip        "The path of the files listed below."
  EndArgument
  Argument         item:1
    Mandatory      1
    LabelString    "File"
    Tooltip        "The file name."
  EndArgument
End

InsetLayout "Flex:FramePic"
  Category         "Hagenberg"
  LyxType          custom
  Decoration       Classic
  LabelType        Static
  LabelString      FramePic
  LatexType        Command
  LatexName        FramePic
  ResetsFont true
End

InsetLayout "Flex:verb (!)"
  LabelString	"verbatim"
  LyxType	charstyle
  LatexType	Command
  LatexName	verb
  ResetFont	1
  Argument 1
    LabelString	"Verbatim Content (!)"
    AutoInsert	1
    LeftDelim	!
    RightDelim	!
  EndArgument
End

Style "No Widows"
  LatexType        Environment
  LatexName        nowidows
  InTitle          false
End